### ISSUE TITLE
DT1: Testing Router

### ISSUE THREAD

**Issue by LicetLemus** [abengl/DEV015-dataverse-chat#13]
- [x] Escribir las pruebas para las funcionalidades de router.js
- [x] Cobertura > 70%

**Comment by abengl** [comment]
A preguntar dónde irían las pruebas unitarias del archivo route.js, si dentro del archivo de tests de funciones o en un archivo distinto.

**Comment by abengl** [comment]
- [x] Empezamos con las pruebas unitarias de las funciones setRoot, setRoutes, queryStringToObject 45% cobertura.

**Comment by abengl** [comment]
- [x] Test unitarios renderView. Cobertura 67%
