### ISSUE TITLE
CA4: Visualizar el set de Datos

### ISSUE THREAD

**Issue by LicetLemus** [abengl/DEV015-dataverse-chat#17]
- [x] Realizar modificaciones en el archivo Home.js ubicado en la carpeta views. Este archivo debe contener el código necesario para visualizar el conjunto de datos. Ten en cuenta que, en este caso, cada vista deberá retornar un elemento para que pueda ser renderizado por el router. Es probable que necesites adaptar el código de tu vista anterior para que modifique un nuevo elemento dentro de esta vista Home.js

```
// src/views/Home.js

import { data } from '../data/dataset.js';
import { filterData } from '../lib/dataFunctions.js';

export function Home(props) {
  const viewEl = document.createElement('div');
  //Modificariamos el contenido del nuevo elemento con lo realizado en Dataverse
  viewEl.innerHTML = `
    <h1>DataVerse</h1>
    ...
  `;
  return viewEl;
}
```

**Comment by abengl** [comment]
![Image](https://github.com/abengl/DEV015-dataverse-chat/assets/126703861/5e820f22-f1f0-4654-8e4b-953a73a4683e)
