### ISSUE TITLE
DT1: Testing Global Migración

### ISSUE THREAD

**Issue by LicetLemus** [abengl/DEV015-dataverse-chat#19]
- [x] Pruebas unitarias de las funciones migradas se ejecuten y tengan cobertura del 70%.
- [x] Pruebas unitarias de las funciones de router.
- [x] Funciones del home (filtrar, ordenar, limpiar y métricas) retornen el resultado esperado en localhost.

**Comment by abengl** [comment]
- This issue must be closed when #13 is completed.
