### ISSUE TITLE
CA3: Chat Individual - Vista que incluya los detalles de la tarjeta

### ISSUE THREAD

**Issue by LicetLemus** [abengl/DEV015-dataverse-chat#21]
- [x] Adaptar el component card o crear este componente.
- [x] Crear el componente para la versión mobile (asegurarse en el media query que no se muestren los detalles, solo el chat). 
- [x] Aplicar estilos al componente
- [x] Renderizar los datos para cada tecnología.

**Comment by abengl** [comment]
![image](https://github.com/abengl/DEV015-dataverse-chat/assets/126703861/aa2ed500-e753-40f6-92f9-ae1ba2155c00)
Planeamos colocar este componente al lado izquierdo de la vista, similar a esta imagen del chat grupal.

**Comment by abengl** [comment]
- El ajuste de query queda a cargo de @LicetLemus , relacionado al #3
